### ISSUE TITLE
Temperature conversions do not work with BinaryCalculator

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#118]
### Summary

_See title._

### Steps to reproduce

1. Open `bin/benchmark` in your editor.
1. Modify the converter to use the BinaryCalculator:

    ```diff
    $converter = \UnitConverter\UnitConverter::createBuilder()
        ->addDefaultRegistry()
    -   ->addSimpleCalculator()
    +   ->addBinaryCalculator()
        ->build();
    ```

1. Modify the unit parameters for conversion:

    ```php
    $converter->convert($values[$i])->from('F')->to('C');
    ```

1. Save the file.
1. Execute the script.

    ```bash
    $ php -f bin/benchmark
    ```

### What is the current *bug* behavior?

Parameter type is not right. It is hard-coded as an integer..

### What is the expected *correct* behavior?

Should work the same as `SimpleCalculator`.

### Relevant logs and/or screenshots

```
Fatal error: Uncaught TypeError: bcdiv() expects parameter 1 to be string, integer given in ~/code/unit-converter/src/UnitConverter/Calculator/BinaryCalculator.php:43
Stack trace:
#0 ~/code/unit-converter/src/UnitConverter/Calculator/BinaryCalculator.php(43): bcdiv(5, 9)
#1 ~/code/unit-converter/src/UnitConverter/Unit/Temperature/Fahrenheit.php(33): UnitConverter\Calculator\BinaryCalculator->div(5, 9)
#2 ~/code/unit-converter/src/UnitConverter/Unit/AbstractUnit.php(72): UnitConverter\Unit\Temperature\Fahrenheit->calculate(Object(UnitConverter\Calculator\BinaryCalculator), 609431, Object(UnitConverter\Unit\Temperature\Celsius), NULL)
#3 ~/code/unit-converter/src/UnitConverter/UnitConverter.php(252): UnitConverter\Unit\AbstractUnit->convert(Object(UnitConverter\Calculator\BinaryCalculator), 609431, Object(UnitConverter\Unit\Temperature\Celsius), NULL)
#4 ~/code/unit-converter/src/UnitConverter/UnitConverter.php(221): UnitConverter\UnitConverter->calculate(609431, O in ~/code/unit-converter/src/UnitConverter/Calculator/BinaryCalculator.php on line 43
```

### Possible fixes

Update the calculator usage within self conversions to use strings instead of integers/floats (see usage in these files).
* [Celsius.php:39](https://github.com/jordanbrauer/unit-converter/blob/master/src/UnitConverter/Unit/Temperature/Celsius.php#L39)
* [Fahrenheit:33](https://github.com/jordanbrauer/unit-converter/blob/master/src/UnitConverter/Unit/Temperature/Fahrenheit.php#L33)

**Comment by jordanbrauer** [comment]
This is fixed in #116.
